# AMMF多语言配置文件
# 格式: lang_[语言代码]() { ... }
# 支持的语言代码: en(英语), zh(中文), jp(日语), ru(俄语), fr(法语)
# 添加新语言时，只需按照相同格式添加新的语言函数

# 英语
lang_en() {
    # 系统消息
    ERROR_TEXT="Error"
    ERROR_CODE_TEXT="Error code"
    ERROR_UNSUPPORTED_VERSION="Unsupported version"
    ERROR_VERSION_NUMBER="Version number"
    ERROR_UPGRADE_ROOT_SCHEME="Please upgrade the root scheme or change the root scheme"
    ERROR_INVALID_LOCAL_VALUE="The value is invalid, must be true or false."
    KEY_VOLUME="Volume key"
    
    # 自定义脚本相关
    CUSTOM_SCRIPT_DISABLED="CustomScript is disabled. Custom scripts will not be executed."
    CUSTOM_SCRIPT_ENABLED="CustomScript is enabled. Executing custom scripts."
    
    # 网络相关
    INTERNET_CONNET="Network available"
    DOWNLOAD_SUCCEEDED="File downloaded"
    DOWNLOAD_FAILED="Download failed"
    RETRY_DOWNLOAD="Retry"
    SKIP_DOWNLOAD="Skip"
    CHECK_NETWORK="No network connection Please check the network connection"
    PRESS_VOLUME_RETRY="Continue retry"
    PRESS_VOLUME_SKIP="Skip"
    DOWNLOADING="Downloading"
    FAILED_TO_GET_FILE_SIZE="Failed to get file size"
    
    # 命令相关
    COMMAND_FAILED="Command failed"
    NOTFOUND_URL="No matching download URL found"
    OUTPUT="Output"
    END="Installation end"
    
    # 菜单相关
    MENU_TITLE_GROUP="======== Group selection ========"
    MENU_TITLE_CHAR="======== Character selection ========"
    MENU_CURRENT_CANDIDATES="Current candidate characters:"
    MENU_CURRENT_GROUP="Current group:"
    MENU_INSTRUCTIONS="VOL+ select | VOL- switch"
    
    # 输入相关
    PROMPT_ENTER_NUMBER="Please enter a number"
    ERROR_INVALID_INPUT="Invalid input!"
    ERROR_OUT_OF_RANGE="Out of range!"
    RESULT_TITLE="Selection result:"

        # Service脚本相关
    SERVICE_STARTED="Service started"
    SERVICE_PAUSED="Entered pause mode, monitoring file"
    SERVICE_NORMAL_EXIT="Service exited normally"
    SERVICE_STATUS_UPDATE="Status updated"
    SERVICE_LOADING_MAIN="Loading main.sh"
    SERVICE_LOADING_SERVICE_SCRIPT="Loading service_script.sh"
    SERVICE_FILE_NOT_FOUND="File not found"
    SERVICE_LOG_ROTATED="Log rotated"
    # WebUI相关
    # WebUI相关
    WEBUI_TITLE="AMMF Settings"
    WEBUI_SAVE="Save"
    WEBUI_LOADING="Loading settings..."
    WEBUI_SAVE_SUCCESS="Settings saved successfully!"
    WEBUI_BOOLEAN_TRUE="Enabled"
    WEBUI_BOOLEAN_FALSE="Disabled"
    WEBUI_LOADING_DESCRIPTIONS="Loading descriptions..."
    WEBUI_LOADING_EXCLUSIONS="Loading exclusions..."
    WEBUI_LOADING_OPTIONS="Loading options..."
    WEBUI_SELECT="Select"
    WEBUI_LANGUAGE_SELECT="Select Language"
    WEBUI_CONFIG_SH_TITLE="Module Configuration"
    WEBUI_SETTINGS_SH_TITLE="Module Settings"
    WEBUI_SYSTEM_PROP_TITLE="System Properties"
    WEBUI_SETTINGS_TITLE="Module Settings"
    WEBUI_SETTINGS_DESCRIPTION="Configure AMMF module parameters"
    WEBUI_SYSTEM_PROP_DESCRIPTION="Edit system properties in system.prop file"
    WEBUI_LOGS_TITLE="Logs"
    WEBUI_LOGS_DESCRIPTION="View module logs"
    WEBUI_ABOUT_TITLE="About"
    WEBUI_ABOUT_DESCRIPTION="View module information and version"
    WEBUI_BACK="Back"
    WEBUI_CONFIG_FILE="Config file:"
    WEBUI_ABOUT_INFO="AMMF Module - A Magisk/KernelSU Module Framework"
    WEBUI_NO_PROPERTIES="No system properties"
    WEBUI_ADD_PROPERTY_HINT="Click the \"Add Property\" button below to add new system properties"
    WEBUI_PROPERTY_NAME="Property Name"
    WEBUI_PROPERTY_VALUE="Property Value"
    WEBUI_ADD_PROPERTY="Add Property"
    WEBUI_STATUS_TITLE="Module Status"
    WEBUI_STATUS_LABEL="Current status:"
    WEBUI_UPTIME_LABEL="Uptime:"
    WEBUI_REFRESH_STATUS="Refresh"
    WEBUI_RESTART_MODULE="Restart Module"
    WEBUI_REFRESH_LOGS="Refresh Logs"
    WEBUI_CLEAR_LOGS="Clear Logs"
    WEBUI_FILTER_LOGS="Filter Logs"
    WEBUI_NO_LOGS="No logs available"
    WEBUI_CONFIRM_CLEAR_LOGS="Are you sure you want to clear all logs?"
    WEBUI_LOGS_CLEARED="Logs cleared successfully"
    WEBUI_SYSTEM_PROP_NOT_FOUND="system.prop file not found"
    WEBUI_CREATE_SYSTEM_PROP_HINT="You can create a new system.prop file to add system properties"
    WEBUI_CREATE_SYSTEM_PROP="Create system.prop"
    WEBUI_CREATING_SYSTEM_PROP="Creating system.prop file..."
    WEBUI_SYSTEM_PROP_CREATED="system.prop file created"
    WEBUI_CREATE_SYSTEM_PROP_FAILED="Failed to create system.prop file"
    WEBUI_CONFIRM_RESTART="Settings saved successfully. Do you want to restart the module to apply changes?"
    WEBUI_LANGUAGE_TITLE="Available Languages"
    WEBUI_LANGUAGE_NAME="English"
    
    # 导航相关
    WEBUI_NAV_STATUS="Status"
    WEBUI_NAV_LOGS="Logs"
    WEBUI_NAV_SETTINGS="Settings"
    WEBUI_NAV_ABOUT="About"
    
    # 通用UI元素
    WEBUI_CANCEL="Cancel"
    WEBUI_CONFIRM="Confirm"
    WEBUI_APPLY="Apply"
    WEBUI_CLOSE="Close"
    WEBUI_DARK_MODE="Dark Mode"
    WEBUI_LIGHT_MODE="Light Mode"
    WEBUI_THEME="Theme"
    WEBUI_LOADING_TEXT="Loading..."
    WEBUI_REFRESH="Refresh"
    WEBUI_SUCCESS="Success"
    WEBUI_ERROR="Error"
    WEBUI_WARNING="Warning"
    WEBUI_SELECT_LANGUAGE="Select Language"
    WEBUI_LANGUAGE_CHANGED="Language changed to English"
    WEBUI_LANGUAGE_CHANGE_RESTART="Language changed. Some changes may require page refresh."
    WEBUI_REFRESH_PAGE="Refresh Page"
}

# 中文
lang_zh() {
    # 系统消息
    ERROR_TEXT="错误"
    ERROR_CODE_TEXT="错误代码"
    ERROR_UNSUPPORTED_VERSION="不支持的版本"
    ERROR_VERSION_NUMBER="版本号"
    ERROR_UPGRADE_ROOT_SCHEME="请升级root方案或更换root方案"
    ERROR_INVALID_LOCAL_VALUE="的值无效，必须为true或false。"
    KEY_VOLUME="音量键"
    
    # 自定义脚本相关
    CUSTOM_SCRIPT_DISABLED="已禁用CustomScript。将不执行自定义脚本。"
    CUSTOM_SCRIPT_ENABLED="已启用CustomScript。正在执行自定义脚本。"
    
    # 网络相关
    INTERNET_CONNET="网络可用"
    DOWNLOAD_SUCCEEDED="已下载文件"
    DOWNLOAD_FAILED="下载失败"
    RETRY_DOWNLOAD="重试"
    SKIP_DOWNLOAD="跳过"
    CHECK_NETWORK="没有网络连接 请检查网络连接"
    PRESS_VOLUME_RETRY="继续重试"
    PRESS_VOLUME_SKIP="跳过"
    DOWNLOADING="下载中"
    FAILED_TO_GET_FILE_SIZE="无法获取文件大小"
    
    # 命令相关
    COMMAND_FAILED="命令失败"
    NOTFOUND_URL="找不到匹配的下载URL"
    OUTPUT="输出"
    END="安装结束"
    
    # 菜单相关
    MENU_TITLE_GROUP="======== 组选择 ========"
    MENU_TITLE_CHAR="======== 字符选择 ========"
    MENU_CURRENT_CANDIDATES="当前候选字符："
    MENU_CURRENT_GROUP="当前组："
    MENU_INSTRUCTIONS="音量+选择 | 音量-切换"
        # Service脚本相关
    SERVICE_STARTED="服务启动"
    SERVICE_PAUSED="进入暂停模式，监控文件"
    SERVICE_NORMAL_EXIT="服务正常退出"
    SERVICE_STATUS_UPDATE="状态更新"
    SERVICE_LOADING_MAIN="加载 main.sh"
    SERVICE_LOADING_SERVICE_SCRIPT="加载 service_script.sh"
    SERVICE_FILE_NOT_FOUND="未找到文件"
    SERVICE_LOG_ROTATED="日志已轮换"
    # 输入相关
    PROMPT_ENTER_NUMBER="请输入一个数字"
    ERROR_INVALID_INPUT="输入无效！"
    ERROR_OUT_OF_RANGE="超出范围！"
    RESULT_TITLE="选择结果："
    
    # WebUI相关
    WEBUI_TITLE="AMMF设置"
    WEBUI_SAVE="保存"
    WEBUI_LOADING="加载设置中..."
    WEBUI_SAVE_SUCCESS="设置保存成功！"
    WEBUI_BOOLEAN_TRUE="已启用"
    WEBUI_BOOLEAN_FALSE="已禁用"
    WEBUI_LOADING_DESCRIPTIONS="加载描述中..."
    WEBUI_LOADING_EXCLUSIONS="加载排除项中..."
    WEBUI_LOADING_OPTIONS="加载选项中..."
    WEBUI_SELECT="选择"
    WEBUI_LANGUAGE_SELECT="选择语言"
    WEBUI_CONFIG_SH_TITLE="模块配置"
    WEBUI_SETTINGS_SH_TITLE="模块设置"
    WEBUI_SYSTEM_PROP_TITLE="系统属性"
    WEBUI_SETTINGS_TITLE="模块设置"
    WEBUI_SETTINGS_DESCRIPTION="配置AMMF模块的各项参数"
    WEBUI_SYSTEM_PROP_DESCRIPTION="编辑system.prop文件中的系统属性"
    WEBUI_LOGS_TITLE="运行日志"
    WEBUI_LOGS_DESCRIPTION="查看模块运行日志"
    WEBUI_ABOUT_TITLE="关于"
    WEBUI_ABOUT_DESCRIPTION="查看模块信息和版本"
    WEBUI_BACK="返回"
    WEBUI_CONFIG_FILE="配置文件:"
    WEBUI_ABOUT_INFO="AMMF模块 - 一个Magisk/KernelSU模块框架"
    WEBUI_NO_PROPERTIES="暂无系统属性"
    WEBUI_ADD_PROPERTY_HINT="点击下方的"添加属性"按钮添加新的系统属性"
    WEBUI_PROPERTY_NAME="属性名"
    WEBUI_PROPERTY_VALUE="属性值"
    WEBUI_ADD_PROPERTY="添加属性"
    WEBUI_STATUS_TITLE="模块状态"
    WEBUI_STATUS_LABEL="当前状态:"
    WEBUI_UPTIME_LABEL="运行时间:"
    WEBUI_REFRESH_STATUS="刷新"
    WEBUI_RESTART_MODULE="重启模块"
    WEBUI_REFRESH_LOGS="刷新日志"
    WEBUI_CLEAR_LOGS="清空日志"
    WEBUI_FILTER_LOGS="筛选日志"
    WEBUI_NO_LOGS="暂无日志"
    WEBUI_CONFIRM_CLEAR_LOGS="确定要清空所有日志吗？"
    WEBUI_LOGS_CLEARED="日志已清空"
    WEBUI_SYSTEM_PROP_NOT_FOUND="system.prop文件不存在"
    WEBUI_CREATE_SYSTEM_PROP_HINT="您可以创建一个新的system.prop文件来添加系统属性"
    WEBUI_CREATE_SYSTEM_PROP="创建system.prop"
    WEBUI_CREATING_SYSTEM_PROP="正在创建system.prop文件..."
    WEBUI_SYSTEM_PROP_CREATED="system.prop文件已创建"
    WEBUI_CREATE_SYSTEM_PROP_FAILED="创建system.prop文件失败"
    WEBUI_CONFIRM_RESTART="保存成功，是否立即重启模块以应用更改？"
    WEBUI_LANGUAGE_TITLE="可用语言"
    WEBUI_LANGUAGE_NAME="简体中文"
    
    # 导航相关
    WEBUI_NAV_STATUS="状态"
    WEBUI_NAV_LOGS="日志"
    WEBUI_NAV_SETTINGS="设置"
    WEBUI_NAV_ABOUT="关于"
    
    # 通用UI元素
    WEBUI_CANCEL="取消"
    WEBUI_CONFIRM="确认"
    WEBUI_APPLY="应用"
    WEBUI_CLOSE="关闭"
    WEBUI_DARK_MODE="深色模式"
    WEBUI_LIGHT_MODE="浅色模式"
    WEBUI_THEME="主题"
    WEBUI_LOADING_TEXT="加载中..."
    WEBUI_REFRESH="刷新"
    WEBUI_SUCCESS="成功"
    WEBUI_ERROR="错误"
    WEBUI_WARNING="警告"
    WEBUI_SELECT_LANGUAGE="选择语言"
    WEBUI_LANGUAGE_CHANGED="已切换到中文"
    WEBUI_LANGUAGE_CHANGE_RESTART="语言已更改。部分更改可能需要刷新页面。"
    WEBUI_REFRESH_PAGE="刷新页面"
}

# 俄语
lang_ru() {
    # 系统消息
    ERROR_TEXT="Ошибка"
    ERROR_CODE_TEXT="Код ошибки"
    ERROR_UNSUPPORTED_VERSION="Неподдерживаемая версия"
    ERROR_VERSION_NUMBER="Номер версии"
    ERROR_UPGRADE_ROOT_SCHEME="Пожалуйста, обновите схему root или измените схему root"
    ERROR_INVALID_LOCAL_VALUE="Значение недействительно, должно быть true или false."
    KEY_VOLUME="Клавиша громкости"
    
    # 自定义脚本相关
    CUSTOM_SCRIPT_DISABLED="CustomScript отключен. Пользовательские скрипты не будут выполняться."
    CUSTOM_SCRIPT_ENABLED="CustomScript включен. Выполнение пользовательских скриптов."
    
    # 网络相关
    INTERNET_CONNET="Сеть доступна"
    DOWNLOAD_SUCCEEDED="Файл загружен"
    DOWNLOAD_FAILED="Ошибка загрузки"
    RETRY_DOWNLOAD="Повторить"
    SKIP_DOWNLOAD="Пропустить"
    CHECK_NETWORK="Нет подключения к сети. Пожалуйста, проверьте подключение к сети"
    PRESS_VOLUME_RETRY="Продолжить повторные попытки"
    PRESS_VOLUME_SKIP="Пропустить"
    DOWNLOADING="Загрузка"
    FAILED_TO_GET_FILE_SIZE="Не удалось получить размер файла"
    
    # 命令相关
    COMMAND_FAILED="Команда не выполнена"
    NOTFOUND_URL="Соответствующий URL для загрузки не найден"
    OUTPUT="Вывод"
    END="Конец установки"
    
    # 菜单相关
    MENU_TITLE_GROUP="======== Выбор группы ========"
    MENU_TITLE_CHAR="======== Выбор символа ========"
    MENU_CURRENT_CANDIDATES="Текущие символы-кандидаты:"
    MENU_CURRENT_GROUP="Текущая группа:"
    MENU_INSTRUCTIONS="VOL+ выбрать | VOL- переключить"
    # Service脚本相关
    SERVICE_STARTED="Служба запущена"
    SERVICE_PAUSED="Вход в режим паузы, мониторинг файла"
    SERVICE_NORMAL_EXIT="Служба завершена нормально"
    SERVICE_STATUS_UPDATE="Статус обновлен"
    SERVICE_LOADING_MAIN="Загрузка main.sh"
    SERVICE_LOADING_SERVICE_SCRIPT="Загрузка service_script.sh"
    SERVICE_FILE_NOT_FOUND="Файл не найден"
    SERVICE_LOG_ROTATED="Журнал ротирован"
    # 输入相关
    PROMPT_ENTER_NUMBER="Пожалуйста, введите число"
    ERROR_INVALID_INPUT="Неверный ввод!"
    ERROR_OUT_OF_RANGE="Вне диапазона!"
    RESULT_TITLE="Результат выбора:"
    
    # WebUI相关
    WEBUI_TITLE="Настройки AMMF"
    WEBUI_SAVE="Сохранить"
    WEBUI_LOADING="Загрузка настроек..."
    WEBUI_SAVE_SUCCESS="Настройки успешно сохранены!"
    WEBUI_SAVE_ERROR="Ошибка сохранения настроек"
    WEBUI_BOOLEAN_TRUE="Включено"
    WEBUI_BOOLEAN_FALSE="Отключено"
    WEBUI_LOADING_DESCRIPTIONS="Загрузка описаний..."
    WEBUI_LOADING_EXCLUSIONS="Загрузка исключений..."
    WEBUI_LOADING_OPTIONS="Загрузка опций..."
    WEBUI_SELECT="Выбрать"
    WEBUI_LANGUAGE_SELECT="Выбрать язык"
    WEBUI_LANGUAGE_TITLE="Доступные языки"
    WEBUI_LANGUAGE_NAME="Русский"
    # ... 现有WebUI翻译 ...
    WEBUI_CANCEL="Отмена"
    WEBUI_CONFIRM="Подтвердить"
    WEBUI_APPLY="Применить"
    WEBUI_CLOSE="Закрыть"
    WEBUI_DARK_MODE="Темная тема"
    WEBUI_LIGHT_MODE="Светлая тема"
    WEBUI_THEME="Тема"
    WEBUI_SETTINGS_SAVED_RESTART="Настройки сохранены. Требуется перезапуск модуля для применения изменений."
    WEBUI_RESTART_NOW="Перезапустить сейчас"
    WEBUI_RESTART_LATER="Позже"
    WEBUI_SEARCH="Поиск"
    WEBUI_SEARCH_PLACEHOLDER="Поиск настроек..."
    WEBUI_NO_RESULTS="Результаты не найдены"
    WEBUI_LOADING_ERROR="Ошибка загрузки данных"
    WEBUI_RETRY="Повторить"
    WEBUI_CONFIG_SELECTOR="Файл конфигурации"
    WEBUI_LANGUAGE_CHANGED="Язык изменен на русский"
    WEBUI_LANGUAGE_CHANGE_RESTART="Язык изменен. Некоторые изменения могут потребовать обновления страницы."
    WEBUI_REFRESH_PAGE="Обновить страницу"
    
    # 补充缺失的WebUI翻译
    WEBUI_CONFIG_SH_TITLE="Конфигурация модуля"
    WEBUI_SETTINGS_SH_TITLE="Настройки модуля"
    WEBUI_SETTINGS_DESCRIPTION="Настройка параметров модуля AMMF"
    WEBUI_SYSTEM_PROP_DESCRIPTION="Редактирование системных свойств в файле system.prop"
    WEBUI_LOGS_DESCRIPTION="Просмотр журналов модуля"
    WEBUI_ABOUT_DESCRIPTION="Просмотр информации и версии модуля"
    WEBUI_BACK="Назад"
    WEBUI_CONFIG_FILE="Файл конфигурации:"
    WEBUI_ABOUT_INFO="Модуль AMMF - Фреймворк модуля Magisk/KernelSU"
    WEBUI_NO_PROPERTIES="Нет системных свойств"
    WEBUI_ADD_PROPERTY_HINT="Нажмите кнопку \"Добавить свойство\" ниже, чтобы добавить новые системные свойства"
    WEBUI_PROPERTY_NAME="Имя свойства"
    WEBUI_PROPERTY_VALUE="Значение свойства"
    WEBUI_ADD_PROPERTY="Добавить свойство"
    WEBUI_STATUS_TITLE="Статус модуля"
    WEBUI_STATUS_LABEL="Текущий статус:"
    WEBUI_UPTIME_LABEL="Время работы:"
    WEBUI_REFRESH_STATUS="Обновить"
    WEBUI_RESTART_MODULE="Перезапустить модуль"
    WEBUI_REFRESH_LOGS="Обновить журналы"
    WEBUI_CLEAR_LOGS="Очистить журналы"
    WEBUI_FILTER_LOGS="Фильтровать журналы"
    WEBUI_NO_LOGS="Нет доступных журналов"
    WEBUI_CONFIRM_CLEAR_LOGS="Вы уверены, что хотите очистить все журналы?"
    WEBUI_LOGS_CLEARED="Журналы успешно очищены"
    WEBUI_SYSTEM_PROP_NOT_FOUND="Файл system.prop не найден"
    WEBUI_CREATE_SYSTEM_PROP_HINT="Вы можете создать новый файл system.prop для добавления системных свойств"
    WEBUI_CREATE_SYSTEM_PROP="Создать system.prop"
    WEBUI_CREATING_SYSTEM_PROP="Создание файла system.prop..."
    WEBUI_SYSTEM_PROP_CREATED="Файл system.prop создан"
    WEBUI_CREATE_SYSTEM_PROP_FAILED="Не удалось создать файл system.prop"
        WEBUI_CONFIRM_RESTART="Настройки успешно сохранены. Вы хотите перезапустить модуль для применения изменений?"  # 新增确认重启提示
    WEBUI_LANGUAGE_TITLE="Доступные языки"  # 补充语言标题
    
    # 在现有WEBUI_LANGUAGE_CHANGED下方补充
    WEBUI_LANGUAGE_CHANGED="Язык изменен на русский"
    WEBUI_LANGUAGE_CHANGE_RESTART="Язык изменен. Некоторые изменения могут потребовать обновления страницы."  # 新增语言切换提示
    
    # 补充缺失的导航条目
    WEBUI_NAV_STATUS="Статус"
    WEBUI_NAV_LOGS="Журналы"
    WEBUI_NAV_SETTINGS="Настройки"
    WEBUI_NAV_ABOUT="О модуле"
    
    # 补充通用操作提示
    WEBUI_REFRESH_PAGE="Обновить страницу"
    WEBUI_RESTART_NOW="Перезапустить сейчас" 
    WEBUI_RESTART_LATER="Позже"
}
